#!/bin/bash
#
# Perform necessary puppet setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

prefix="blacklight-"
puppet_services="puppet-agent " #puppet-master puppet-queue"
install_base="/opt/blacklight/puppet"

exit 0
